
service: aws-python3 # NOTE: update this with your service name

provider:
  name: aws
  runtime: python3.7
  tracing: true
  iamRoleStatements:
  - Effect: "Allow"
    Action:
    - "dynamodb:PutItem"
    - "dynamodb:GetItem"
    Resource:
    - Fn::GetAtt:
      - DynamoDBTable
      - Arn
    - Fn::GetAtt:
      - UrlPreviewTable
      - Arn
  - Effect: "Allow" # xray permissions (required)
    Action:
    - "xray:PutTraceSegments"
    - "xray:PutTelemetryRecords"
    Resource: "*"

package:
  exclude:
  - node_modules/**
  - venv/**

functions:
  create-url:
    handler: handler.create_url  
    events:
    - http:
        path: / 
        method: post
  get-url:
    handler: handler.get_url 
    events:
    - http:
        path: /{short_url} 
        method: get
        request:
          parameters:
            paths:
              short_url: true
  unfurl:
    handler: handler.unfurl
    events:
    - stream:
        type: dynamodb
        arn:
          Fn::GetAtt:
          - DynamoDBTable
          - StreamArn

custom:
  pythonRequirements:
    dockerizePip: true

  alerts:
    stages:
    - dev
    topics:
      alarm:
        topic: ${self:service}-alerts-alarm
        notifications:
        - protocol: email
          endpoint: soenke.ruempler@superluminar.io
    alarms:
    - functionErrors
    - functionThrottles

resources:
  Resources:
    DynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_IMAGE
        TableName: url-shortener 
        KeySchema:
          - AttributeName: "short_url"
            KeyType: "HASH"
        AttributeDefinitions:
          - AttributeName: "short_url"
            AttributeType: "S"

    UrlPreviewTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: url-preview
        KeySchema:
        - AttributeName: "url"
          KeyType: "HASH"
        AttributeDefinitions:
        - AttributeName: "url"
          AttributeType: "S"

    __deployment__:
      Properties:
        Description: This is my deployment
    ApiGatewayStage:
      Type: AWS::ApiGateway::Stage
      Properties:
        TracingEnabled: true # enable x-ray
        DeploymentId:
          Ref: __deployment__
        RestApiId:
          Ref: ApiGatewayRestApi
        StageName: dev
        MethodSettings:
        - HttpMethod: "*"
          ResourcePath: "/*"
          MetricsEnabled: true
          LoggingLevel: INFO
          DataTraceEnabled: true

plugins:
  - serverless-python-requirements
  - serverless-plugin-tracing
  - serverless-plugin-bind-deployment-id
  - serverless-plugin-aws-alerts