name: Continuous Integration
on: push

jobs:
  synth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Synth labs
        run: npm run cdk synth --workspaces
