name: Continuous Integration
on: push

jobs:
  synth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install dependencies
        run: npm ci
      - name: Synth labs
        run: npm run synth:all
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install dependencies
        run: npm ci
      - name: Unit Tests
        run: npm run test:all
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v16
      - name: File Changes Detected
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Please run eslint or update the snapshots. Commit the changes and try again. 🤭"
          exit 1
